SistemaPrestamo/Prestamo.Web/Controllers/LoginController.cs
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Prestamo.Data;
using Prestamo.Entidades;
using System.Security.Claims;
using System.Threading.Tasks;
using System.Collections.Generic;
using System.Diagnostics;
using Microsoft.IdentityModel.Tokens;
using System.IdentityModel.Tokens.Jwt;
using System.Text;
using Microsoft.AspNetCore.Authentication.JwtBearer;


namespace Prestamo.Web.Controllers
{
    public class LoginController : Controller
    {
        private readonly UsuarioData _usuarioData;
        private readonly EmailService _emailService;
        private readonly IConfiguration _configuration;

        public LoginController(UsuarioData usuarioData, EmailService emailService, IConfiguration configuration )
        {
            _usuarioData = usuarioData;
            _emailService = emailService;
            _configuration = configuration;
        }
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Index(string correo, string clave)
        {
            if (string.IsNullOrEmpty(correo) || string.IsNullOrEmpty(clave))
            {
                ViewData["Mensaje"] = "Todos los campos son obligatorios";
                return View();
            }

            // Obtener el usuario por correo
            var usuario = await _usuarioData.ObtenerPorCorreo(correo);
            if (usuario == null)
            {
                ViewData["Mensaje"] = "Usuario no encontrado";
                return View();
            }

            // Verificar si el usuario está bloqueado
            if (usuario.IsLocked)
            {
                if (usuario.LockoutEnd > DateTime.UtcNow)
                {
                    ViewData["Mensaje"] = "Su cuenta está bloqueada. Por favor, contacte al administrador.";
                    return View();
                }
                else
                {
                    // Si el tiempo de bloqueo ha pasado, resetear el estado
                    await _usuarioData.ResetLockout(usuario.IdUsuario);
                }
            }

            // Verificar si hay un bloqueo temporal activo
            if (usuario.LockoutEnd != null && usuario.LockoutEnd > DateTime.UtcNow)
            {
                var tiempoRestante = (usuario.LockoutEnd.Value - DateTime.UtcNow).TotalSeconds;
                Console.WriteLine($"Tiempo restante: {tiempoRestante}");
                // Asegurar que no se redondee a 0
                if (tiempoRestante > 0)
                {
                    ViewData["Mensaje"] = $"Por favor espere {(int)tiempoRestante} segundos antes de intentar nuevamente.";
                    ViewData["TiempoBloqueado"] = (int)Math.Ceiling(tiempoRestante); // Redondear hacia arriba
                    Console.WriteLine($"Tiempo bloqueado: {tiempoRestante}");
                    Console.WriteLine(ViewData["TiempoBloqueado"]);
                    return View();
                }
                else
                {
                    ViewData["TiempoBloqueado"] = null; // Evitar valores incorrectos
                }
            }

            // Verificar la contraseña
            if (string.IsNullOrEmpty(usuario.Clave))
            {
                ViewData["Mensaje"] = "Error al recuperar la contraseña del usuario";
                return View();
            }

            bool isPasswordValid = BCrypt.Net.BCrypt.Verify(clave, usuario.Clave);

            if (!isPasswordValid)
            {
                usuario.FailedAttempts++;
                usuario.LastFailedAttempt = DateTime.UtcNow;

                int tiempoBloqueado = 0;
                if (usuario.FailedAttempts == 3)
                {
                    tiempoBloqueado = 15;
                    usuario.LockoutEnd = DateTime.UtcNow.AddSeconds(tiempoBloqueado);
                }
                else if (usuario.FailedAttempts == 4)
                {
                    tiempoBloqueado = 30;
                    usuario.LockoutEnd = DateTime.UtcNow.AddSeconds(tiempoBloqueado);
                }
                else if (usuario.FailedAttempts >= 5)
                {
                    usuario.IsLocked = true;
                    usuario.LockoutEnd = DateTime.MaxValue;
                    await _usuarioData.UpdateLockoutStatus(usuario);
                    ViewData["Mensaje"] = "Su cuenta ha sido bloqueada permanentemente. Contacte al administrador.";
                    return View();
                }

                await _usuarioData.UpdateLockoutStatus(usuario);

                if (tiempoBloqueado > 0)
                {
                    ViewData["Mensaje"] = "Demasiados intentos fallidos. Su cuenta está bloqueada temporalmente.";
                    ViewData["TiempoBloqueado"] = tiempoBloqueado;
                    return View();
                }

                ViewData["Mensaje"] = $"Contraseña incorrecta. Intentos restantes: {3 - usuario.FailedAttempts}";
                return View();
            }

            // Login exitoso - resetear contadores
            await _usuarioData.ResetLockout(usuario.IdUsuario);

            // Generar código de verificación
            var codigoVerificacion = new Random().Next(100000, 999999).ToString();
            HttpContext.Session.SetString("CodigoVerificacion", codigoVerificacion);
            HttpContext.Session.SetString("CorreoVerificacion", correo);

            // Enviar código de verificación por correo
            string asunto = "Código de verificación";
            string mensaje = $"Tu código de verificación es: {codigoVerificacion}";
            await _emailService.EnviarCorreoAsync(correo, asunto, mensaje);

            // Aquí guardamos la información de nuestro usuario
            var claims = new[]
            {
                new Claim(ClaimTypes.Name, usuario.NombreCompleto),
                new Claim(ClaimTypes.NameIdentifier, usuario.IdUsuario.ToString()),
                new Claim(ClaimTypes.Email, usuario.Correo),
                new Claim(ClaimTypes.Role, usuario.Rol)
            };

            var key = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(_configuration["Jwt:Key"]!));
            var credentials = new SigningCredentials(key, SecurityAlgorithms.HmacSha256);
            var expires = DateTime.Now.AddMinutes(Convert.ToDouble(_configuration["Jwt:expires"]));

            var token = new JwtSecurityToken(
                _configuration["Jwt:Issuer"],
                _configuration["Jwt:Audience"],
                claims,
                expires: expires,
                signingCredentials: credentials
            );

            HttpContext.Session.SetString("Token", new JwtSecurityTokenHandler().WriteToken(token));
            TempData["Token"] = new JwtSecurityTokenHandler().WriteToken(token);
            return RedirectToAction("VerificarCodigo");
        }

        public IActionResult VerificarCodigo()
        {
            ViewData["Token"] = TempData["Token"];
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> VerificarCodigoAsync(string codigo)
        {
            var codigoVerificacion = HttpContext.Session.GetString("CodigoVerificacion");
            var correo = HttpContext.Session.GetString("CorreoVerificacion");
            var token = HttpContext.Session.GetString("Token");

            if (codigo == codigoVerificacion)
            {
                var usuario = _usuarioData.ObtenerPorCorreo(correo!).Result;
                // Crear identidad del usuario
                var claims = new List<Claim>
                {
                    new Claim(ClaimTypes.Name, usuario.NombreCompleto),
                    new Claim(ClaimTypes.Email, usuario.Correo),
                    new Claim(ClaimTypes.Role, usuario.Rol)
                };

                var identity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);
                var principal = new ClaimsPrincipal(identity);

                // Generar cookie de autenticación
                await HttpContext.SignInAsync(
                    CookieAuthenticationDefaults.AuthenticationScheme,
                    principal,
                    new AuthenticationProperties { IsPersistent = false }
                );

                // Opcional: Guardar JWT en cookie adicional
                Response.Cookies.Append("access_token", token, new CookieOptions
                {
                    HttpOnly = true,
                    Secure = true
                });

                return RedirectToAction("Index", "Home");
            }
            else
            {
                ViewData["Mensaje"] = "Código de verificación incorrecto";
                return View();
            }
        }

        public async Task<IActionResult> Salir()
        {
            await HttpContext.SignOutAsync(JwtBearerDefaults.AuthenticationScheme);
            return RedirectToAction("Index", "Login");
        }
    }
}

SistemaPrestamo/Prestamo.Web/Controllers/RegisterController.cs
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using Prestamo.Data;
using Prestamo.Entidades;
using System.Security.Claims;
using System.Text.RegularExpressions;
using System.Threading.Tasks;

namespace Prestamo.Web.Controllers
{
    public class RegisterController : Controller
    {
        private readonly UsuarioData _usuarioData;

        public RegisterController(UsuarioData usuarioData)
        {
            _usuarioData = usuarioData;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Index(string nombreCompleto, string correo, string clave)
        {
            if (string.IsNullOrEmpty(nombreCompleto) || string.IsNullOrEmpty(correo) || string.IsNullOrEmpty(clave))
            {
                ViewData["Mensaje"] = "Todos los campos son obligatorios";
                return View();
            }

            if (!Regex.IsMatch(correo, @"^[^@\s]+@[^@\s]+\.[^@\s]+$"))
            {
                ViewData["Mensaje"] = "Correo electrónico no válido";
                return View();
            }

            // Verificar si el correo ya está registrado
            var usuarioExistente = await _usuarioData.ObtenerPorCorreo(correo);
            if (usuarioExistente != null)
            {
                ViewData["Mensaje"] = "El correo electrónico ya está registrado";
                return View();
            }

            // Hashing de la contraseña
            string hashedClave = BCrypt.Net.BCrypt.HashPassword(clave);

            Usuario nuevoUsuario = new Usuario
            {
                NombreCompleto = nombreCompleto,
                Correo = correo,
                Clave = hashedClave,
                Rol = "Administrador" // Asignar rol automáticamente
            };

            bool usuarioCreado = await _usuarioData.Crear(nuevoUsuario);

            if (!usuarioCreado)
            {
                ViewData["Mensaje"] = "Error al crear el usuario";
                return View();
            }

            ViewData["Mensaje"] = "Usuario creado exitosamente";

            // Aquí guardamos la información de nuestro usuario
            List<Claim> claims = new List<Claim>
            {
                new Claim(ClaimTypes.Name, nuevoUsuario.NombreCompleto),
                new Claim(ClaimTypes.NameIdentifier, nuevoUsuario.IdUsuario.ToString()),
                new Claim(ClaimTypes.Role, nuevoUsuario.Rol)
            };

            ClaimsIdentity claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);
            AuthenticationProperties properties = new AuthenticationProperties
            {
                AllowRefresh = true
            };

            await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(claimsIdentity), properties);
            return RedirectToAction("Index", "Home");
        }
    }
}

SistemaPrestamo/Prestamo.Web/Views/Login/Index.cshtml
@{
    Layout = null;
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Login - SB Admin</title>
    <link href="~/css/styles.css" rel="stylesheet" />
    <script src="~/lib/fontawesome/all.js"></script>
</head>
<body class="bg-primary">
    <div id="layoutAuthentication">
        <div id="layoutAuthentication_content">
            <main>
                <div class="container">
                    <div class="row justify-content-center">
                        <div class="col-lg-5">
                            <div class="card shadow-lg border-0 rounded-lg mt-5">
                                <div class="card-header"><h3 class="text-center font-weight-light my-4">Login</h3></div>
                                <div class="card-body">

                                    <div id="lockoutMessage" class="sb-alert d-none">
                                        <div class="text-center">
                                            <p class="mb-1">Cuenta bloqueada temporalmente</p>
                                            <p class="mb-0">Tiempo restante: <span id="countdown">0</span> segundos</p>
                                        </div>
                                    </div>

                                    <div id="errorMessage" class="sb-alert-danger d-none"></div>
                                    
                                    <form asp-controller="Login" asp-action="Index" method="post">
                                        <div class="form-floating mb-3">
                                            <input class="form-control" type="email" placeholder="Nombre usuario" name="correo" required />
                                            <label for="inputEmail">Correo</label>
                                        </div>
                                        <div class="form-floating mb-3">
                                            <input class="form-control" type="password" placeholder="Contraseña" name="clave" required />
                                            <label for="inputPassword">Contraseña</label>
                                        </div>
                                        
                                        @if (ViewData["Mensaje"] != null)
                                        {
                                            <div class="form-group">
                                                <div class="alert alert-danger" role="alert" id="alerta1">
                                                    @ViewData["Mensaje"]
                                                </div>
                                            </div>
                                        }
                                        @if (ViewData["TiempoBloqueado"] != null)
                                        {
                                            <div class="alert alert-warning" role="alert" id="alerta">
                                                <p><strong>Tiempo restante:</strong> <span id="tiempo"></span> segundos</p>
                                            </div>
                                            <script>
                                                // Guardar directamente en localStorage desde el backend
                                                localStorage.setItem("TiempoBloqueado", "@ViewData["TiempoBloqueado"]");
                                                console.log("Tiempo bloqueado guardado en localStorage:", localStorage.getItem("TiempoBloqueado"));
                                            </script>
                                        }
                                        
                                        <div class="d-flex align-items-center justify-content-between mt-4 mb-0">
                                            <button type="submit" class="btn btn-primary" id="btnlogin">Iniciar Sesión</button>
                                        </div>
                                       
                                    </form>
                                </div>
                                <div class="card-footer text-center py-3">
                                    <div class="small">
                                        <a href="@Url.Action("Index", "Register")">¿No tienes una cuenta? Regístrate aquí</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </main>
        </div>
        <div id="layoutAuthentication_footer">
            <footer class="py-4 bg-light mt-auto">
                <div class="container-fluid px-4">
                    <div class="d-flex align-items-center justify-content-between small">
                        <div class="text-muted">Copyright &copy; Your Website 2023</div>
                        <div>
                            <a href="#">Privacy Policy</a>
                            &middot;
                            <a href="#">Terms &amp; Conditions</a>
                        </div>
                    </div>
                </div>
            </footer>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/scripts.js"></script>
</body>
</html>

SistemaPrestamo/Prestamo.Web/Views/Login/VerificarCodigo.cshtml
@{
    Layout = null;
    var token = ViewData["Token"] as string;
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Verificar Código - SB Admin</title>
    <link href="~/css/styles.css" rel="stylesheet" />
    <script src="~/lib/fontawesome/all.js"></script>
</head>
<body class="bg-primary">
    <div id="layoutAuthentication">
        <div id="layoutAuthentication_content">
            <main>
                <div class="container">
                    <div class="row justify-content-center">
                        <div class="col-lg-5">
                            <div class="card shadow-lg border-0 rounded-lg mt-5">
                                <div class="card-header"><h3 class="text-center font-weight-light my-4">Verificar Código</h3></div>
                                <div class="card-body">
                                    <form asp-controller="Login" asp-action="VerificarCodigo" method="post">
                                        <div class="form-floating mb-3">
                                            <input class="form-control" type="text" placeholder="Código de verificación" name="codigo" required />
                                            <label for="inputCodigo">Código de verificación</label>
                                        </div>
                                        @if (ViewData["Mensaje"] != null)
                                        {
                                            <div class="form-group">
                                                <div class="alert alert-danger" role="alert">
                                                    @ViewData["Mensaje"]
                                                </div>
                                            </div>
                                        }

                                        <div class="d-flex align-items-center justify-content-between mt-4 mb-0">
                                            <button type="submit" class="btn btn-primary">Verificar</button>
                                        </div>
                                    </form>
                                </div>
                                <div class="card-footer text-center py-3">
                                    <div class="small">
                                        <a href="@Url.Action("Index", "Login")">Volver al login</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </main>
        </div>
        <div id="layoutAuthentication_footer">
            <footer class="py-4 bg-light mt-auto">
                <div class="container-fluid px-4">
                    <div class="d-flex align-items-center justify-content-between small">
                        <div class="text-muted">Copyright &copy; Your Website 2023</div>
                        <div>
                            <a href="#">Privacy Policy</a>
                            &middot;
                            <a href="#">Terms &amp; Conditions</a>
                        </div>
                    </div>
                </div>
            </footer>
        </div>
    </div>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script>
        document.addEventListener('DOMContentLoaded', function () {
            const token = '@token';
            console.log('Token1:', token);
            if (token) {
                localStorage.setItem('token', token);
                console.log('Token2:', token);
            }
        });
    </script>
</body>
</html>